account/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    # post views
    # url(r'^login/$', views.user_login, name='login'),
    url(r'^login/$', auth_views.login, {'template_name': 'account/login.html'}, name='login'),
    url(r'^dashboard/$', views.dashboard, name='dashboard'),
    url(r'^logout/$', auth_views.logout, {'template_name': 'account/logged_out.html'}, name='logout'),
    url(r'^logout-then-login/$', auth_views.logout_then_login, name='logout_then_login'),
    # change password urls
    url(r'^password-change/$', auth_views.password_change, {'template_name': 'account/password_change.html'}, name='password_change'),
    url(r'^password-change/done/$', auth_views.password_change_done, name='password_change_done'),
    # password reset by e-mail, cf django book for recipe

    # new user registration
    url(r'^register/$', views.register, name='register'),
    url(r'^edit/$', views.edit, name='edit')
]

hitarget/urls.py
from . import views
from django.conf.urls import url
from . import views

urlpatterns = [
    # post views
    url(r'^$', views.home, name='home'),
    url(r'blank', views.blank, name='blank'),
    url(r'add', views.add_lead, name='add_lead'),
    url(r'my-leads', views.my_leads, name='my-leads'),
    url(r'tips', views.tips, name='tips'),
    url(r'search_leads', views.search_leads, name='search_leads'),

    url(r'(?P<slug>[-\w]+?)/full$', views.lead_detail_full, name='lead_detail_full'),
    url(r'(?P<slug>[-\w]+?)/$', views.lead_detail, name='lead_detail'),
    url(r'(?P<slug>[-\w]+?)/edit$', views.lead_edit, name='lead_edit'),
    url(r'(?P<slug>[-\w]+?)/delete$', views.lead_delete, name='lead_delete'),
]

hitargetMVP/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^account/', include(arg='account.urls'


                            )),
    url(r'^leads/', include(arg='hitarget.urls',
                            namespace="hitarget",
                            app_name="hitarget",
                            ))
]

# specific workaround to serve user images
if settings.SETTING == "DEBUG":
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

hitarget/forms.py
import itertools

import re

from django import forms
from django.utils.text import slugify

from .models import Lead
from django.utils.translation import ugettext as _


class AddLeadForm(forms.ModelForm):
    # title = forms.CharField()
    # location = forms.CharField()
    # description_short = forms.CharField()
    # categories = forms.CharField()
    # contact_name = forms.CharField()
    # contact_phone = forms.CharField()
    # contact_email = forms.EmailField()
    # description_full = forms.CharField()
    title = forms.CharField(max_length=180,
                            min_length=8, strip=True,
                            # initial=_("Infrastructure d'impression laser"),
                            widget=forms.TextInput(attrs={'placeholder': _("Infrastructure d'impression laser")}),
                            help_text="Donnez un titre court, incisif et direct. 140 caractères semble être une bonne pratique",
                            label=_("Un titre"),
                            error_messages={
                                "required": _("Il faut donner un titre!"),
                                "min_length": _("Un peu plus d'informations dans le titre")
                            })

    location = forms.CharField(max_length=120,
                               min_length=2, strip=True,
                               # initial=_("Infrastructure d'impression laser"),
                               widget=forms.TextInput(attrs={'placeholder': _("Martillac")}),
                               help_text="Un code postal, une région, une grande ville ou un petit village: on arrivera toujours à le localiser",
                               label=_("Un lieu"),
                               error_messages={
                                   "required": _("Il nous faut un lieu!"),
                                   "min_length": _("Plus d'informations sur le lieu ?")
                               })
    description_short = forms.CharField(max_length=720,
                                        min_length=30, strip=True,
                                        # initial=_("Infrastructure d'impression laser"),
                                        widget=forms.Textarea(attrs={'placeholder': _(
                                            "Un très bon client dans le secteur agro-alimentaire cherche à moderniser ses 250 centres d'impressions.")}),
                                        help_text="",
                                        label=_("Un résumé du besoin"),
                                        error_messages={
                                            "min_length": _("Au moins une trentaine de caractères pour la description?"),
                                            "required": _("Décrivez-nous le besoin pour que tout le monde puisse le trouver.")
                                        })

    category = forms.CharField(max_length=120,
                               min_length=3, strip=True,
                               # initial=_("Infrastructure d'impression laser"),
                               widget=forms.TextInput(
                                   attrs={'placeholder': _("Informatique; Agro-alimentaire; Boulangerie")}),
                               help_text="",
                               label=_("Des rubriques"),
                               error_messages={
                                   "required": _("Décrivez-vous nous dans quel grand secteur trier votre opportunité"),
                                   "min_length": _("Descriptif des rubriques trop courte")
                               })

    contact_name = forms.CharField(max_length=120,
                                   min_length=3, strip=True,
                                   # initial=_("Infrastructure d'impression laser"),
                                   widget=forms.TextInput(
                                       attrs={'placeholder': _("Jean-Pierre Petit")}),
                                   help_text="",
                                   label=_("Comment s'appelle le contact ?"),
                                   error_messages={
                                       "required": _("!! Décrivez-nous le nom de la personne à contacter"),
                                       "min_length": _("!! Nom trop court, êtes vous-sûr de l'avoir bien renseigné?"),
                                   })

    contact_company = forms.CharField(max_length=120,
                                      min_length=3, strip=True,
                                      # initial=_("Infrastructure d'impression laser"),
                                      widget=forms.TextInput(
                                          attrs={'placeholder': _("Boulangeries Le Petit")}),
                                      help_text="",
                                      label=_("Quel est le nom de la société ?"),
                                      error_messages={
                                          "required": _("Décrivez-vous nous le nom de la société à contacter"),
                                          "min_length": _("Nom trop court, êtes vous-sûr de l'avoir bien renseigné?"),
                                      })

    contact_phone_number = forms.CharField(min_length=6, max_length=20,
                                           strip=True,
                                           # initial=_("Infrastructure d'impression laser"),
                                           widget=forms.TextInput(
                                               attrs={'placeholder': _("06 01 02 03 04")}),
                                           help_text="",
                                           label=_("Son téléphone?"),
                                           error_messages={
                                               "required": _("Indiquez soit un e-mail soit un numéro de téléphone pour le contact"),
                                               "min_length": _("Numéro trop court, êtes vous-sûr de l'avoir bien renseigné?"),
                                               "invalid": _("Numéro invalide, êtes vous-sûr de l'avoir bien renseigné?"),
                                           })
    contact_email = forms.EmailField(min_length=6,
                                     strip=True,
                                     # initial=_("Infrastructure d'impression laser"),
                                     widget=forms.TextInput(
                                         attrs={'placeholder': _("jean.pierre.petit@gmail.com")}),
                                     help_text="",
                                     label=_("Son email?"),
                                     error_messages={
                                         "required": _("Indiquez soit un e-mail soit un numéro de téléphone pour le contact"),
                                         "min_length": _("L'email est trop court!"),
                                         "invalid": _("Email invalide, êtes vous-sûr de l'avoir bien renseigné?"),
                                     })

    description_full = forms.CharField(max_length=720,
                                       min_length=30, strip=True,
                                       # initial=_("Infrastructure d'impression laser"),
                                       widget=forms.Textarea(attrs={'placeholder': _(
                                           "M. Petit m'a indiqué rechercher une société pour l'accompagner dans le renouvellement de son parc d'impression, il semble être préssé !")}),
                                       help_text="",
                                       label=_("Un descriptif complet du besoin"),
                                       error_messages={
                                           "min_length": _("Au moins une trentaine de caractères pour la description?"),
                                           "required": _("Décrivez-nous totalement le besoin pour que vos collègues soient le plus informés possible.")
                                       })

    class Meta:
        fields = ['title', 'location', 'description_short', 'category', 'contact_name', 'contact_company', 'contact_phone_number', 'contact_email', 'description_full']
        exclude = ['date_expired', 'slug',
                   'category_entity',
                   'location_entity',
                   'contact_company_entity'
                   ]

        model = Lead

    # we customize the save method to automatically populate some fields
    def save(self, commit=True):
        print("in save")
        instance = super(AddLeadForm, self).save(commit=False)

        max_length = Lead._meta.get_field('slug').max_length
        if not instance.slug:
            print("generating new slug")
            instance.slug = orig = slugify(instance.title)[:max_length]
            for x in itertools.count(1):
                if not Lead.objects.filter(slug=instance.slug).exists():
                    break

                # Truncate the original slug dynamically. Minus 1 for the hyphen.
                instance.slug = "%s-%d" % (orig[:max_length - len(str(x)) - 1], x)
        # assign author to current logged in user
        # instance.author_id=1
        # compute expiration date
        instance.update_expiration_date()
        if commit:
            instance.save()

        return instance

hitarget/views.py
from django.shortcuts import render, redirect
from django.shortcuts import render, get_object_or_404
from django.template import loader
import pprint as pp

from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt

from hitarget.hitarget_faker import fake_lead_add_form_data
from .models import Lead
from .forms import AddLeadForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.utils.translation import ugettext as _


# logger

# import the logging library
import logging

# Get an instance of a logger
logger = logging.getLogger(__name__)

# Create your views here.



def blank(request):
    #     only for development! used as a template for bracket
    return render(
        request=request,
        template_name="hitarget/base.html"
    )


def home(request):
    leads = Lead.objects.all()[0:10]
    return render(
        request=request,
        template_name="hitarget/leads/home.html",
        context={"leads": [lead_mini(request, lead=l) for l in leads]}
    )


def lead_mini(request, lead):
    ff = loader.render_to_string(
        request=request,
        template_name="hitarget/components/lead_mini.html",
        context={"lead": lead, "associated_actions": lead.generate_action_buttons_mini(request)}
    )
    return ff


@login_required
def lead_detail(request, slug):
    lead = get_object_or_404(Lead, slug=slug)
    return render(
        request=request,
        template_name="hitarget/leads/detail.html",
        context={
            "lead_html": lead_maxi(request, lead),
            "lead": lead,
        }
    )


@login_required
def lead_maxi(request, lead):
    return loader.render_to_string(
        request=request,
        template_name="hitarget/components/lead_maxi.html",
        context={"lead": lead, "associated_actions": lead.generate_action_buttons_maxi(request)}
    )


@login_required
def lead_detail_full(request, slug):
    print("getting %s", slug)
    lead = get_object_or_404(Lead, slug=slug)
    if lead.author == request.user:
        messages.info(request, _("Seul vous pouvez voir ces infos"))
    else:
        # TODO add check that lead is actually bought
        messages.info(request, _("Félicitations, ce lead est à vous!"))
    return render(
        request=request,
        template_name="hitarget/leads/detail_full.html",
        context={
            "lead_html": lead_full(request, lead),
            "lead": lead,
        }
    )


@login_required
def lead_full(request, lead):
    return loader.render_to_string(
        request=request,
        template_name="hitarget/components/lead_full.html",
        context={"lead": lead, "associated_actions": lead.generate_action_buttons_maxi(request)}
    )


@login_required
def add_lead(request):
    if request.method == "POST":
        pp.pprint("Received POST data %s" % (request.POST))
        add_lead_form = AddLeadForm(data=request.POST)
        if add_lead_form.is_valid():
            print("is valid")
            new_item = add_lead_form.save(commit=False)
            new_item.author = request.user
            new_item.save()
            # redirect to newly created item
            messages.info(request, _("Votre lead est en ligne, le voici:"))
            return redirect(new_item.get_absolute_url())
        else:
            print("invalid form data")


    elif request.method == "GET":
        add_lead_form = AddLeadForm(initial=fake_lead_add_form_data())
    return render(
        request=request,
        template_name="hitarget/leads/add_or_edit.html",
        context={'add_lead_form': add_lead_form}
    )


def tips(request):
    return render(
        request=request,
        template_name="hitarget/leads/tips.html",
        context={}
    )


@login_required
def lead_edit(request, slug):
    instance = get_object_or_404(Lead, slug=slug)
    # check permission
    current_user = request.user
    print("user %s trying to change lead belonging to %s, can==%s" % (current_user, instance.author, instance.author == current_user))
    # TODO raise 403
    add_lead_form = AddLeadForm(data=request.POST or None, instance=instance)
    if add_lead_form.is_valid():
        print("edition is valid")
        add_lead_form.save()
        messages.info(request, "Lead bien mis à jour")
        return redirect(to=instance.get_absolute_url())
    return render(
        request=request,
        template_name="hitarget/leads/add_or_edit.html",
        context={'add_lead_form': add_lead_form})


def lead_delete(request, slug):
    instance = get_object_or_404(Lead, slug=slug)
    # check permission
    current_user = request.user
    print("[%s]user %s trying to delete lead belonging to %s, can==%s" % (request.method, current_user, instance.author, instance.author == current_user))
    # TODO raise 403
    if request.method == "POST":
        instance.delete()
        messages.info(request, "Votre lead est désormais supprimé")
        return redirect(to=reverse('hitarget:home'))
    else:
        return render(
            request=request,
            template_name="hitarget/leads/delete.html",
            context={"lead": instance}
        )


@login_required
def my_leads(request):
    current_user = request.user
    current_user_leads = current_user.leads.all()
    print("found %d leads for author %s:%s" % (len(current_user_leads), current_user, current_user_leads))
    return render(
        request=request,
        template_name="hitarget/leads/my-leads.html",
        context={"leads": current_user_leads}
    )


@login_required
@csrf_exempt
def search_leads(request):
    print("in search results")
    if request.method=="GET":
        print("Got GET request with params %s",request.GET)
    if request.method=="POST":
        print("Got POST request with params %s",request.POST)

    leads_results = Lead.objects.all()[0:10]
    return render(
        request=request,
        template_name="hitarget/leads/search_results.html",
        context={"leads_results": leads_results}
    )

hitarget/templates/hitarget/components/lead_full.html
{% load l10n %}


<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-6 col-l-6 col-xl-4">
        <div class="panel panel-default">
            <!--<div class="panel-heading">-->
                <!--{{lead.main_title}}-->
                <!--<div class="clearfix"></div>-->
            <!--</div>-->
            <div class="panel-body">
                <h3>De quoi ça parle ?</h3>
                <p>Opportunité dans le domaine {{lead.category|title}}</p>
                <p>{{lead.description_short}}</p>

                <h3>Quand?</h3>
                <ul>
                    <li>Info publiée le {{lead.date_publish|date:"D d M Y"|localize}}
                    <li>Valable pendant {{lead.expires_in_full|lower}}
                </ul>

                <h3>A propos du prospect</h3>
                <ul>
                    <li>Est basé à {{lead.location}}
                    <li>En ce moment: {{lead.prospect_maturity}}
                </ul>

                <h3>Les infos</h3>
                {{lead.description_full}}
                <h4>Le contact</h4>
                <p>{{lead.contact_name | title}}, de la société {{lead.contact_company|title}}</p>
                <p>Où le trouver: {{lead.location | title}}</p>
                <p>Pour le contacter :</p>
                <ul>

                {% if lead.contact_phone_number %}
                    <li>Téléphone: {{lead.contact_phone_number}}</li>
                {% endif %}

                {% if lead.contact_email %}
                    <li>E-mail: {{lead.contact_email}}</li>
                {% endif %}
                </ul>
            </div>


            <h3>A propos de l'auteur</h3>
            <div class="media">
                <a class="pull-left" href="#">
                    <img class="media-object avatar" width="60px" src="{{lead.author_avatar}}"
                         alt="{{lead.author_avatar_alt}}"/>

                </a>
                <div class="media-body">
                    <h4 class="media-heading">{{lead.author | title}}</h4>
                    <ul>
                        <li>est sur HiTarget depuis 3 semaines
                    </ul>

                </div>
            </div>

        </div>
    </div>
    <div>
        <small class="pull-left date">&nbsp;{{lead.relative_date}}</small>
    </div>
    <div class="btn-group btn-group-sm pull-right" role="group" aria-label="...">
        {% for act in associated_actions %}
        <a href="{{act.url}}" class="btn btn-default {{act.additional_class}}" role="button"><i
                class="glyphicon {{act.icon}}"></i>{{act.text}}</a>
        {% endfor %}

    </div>
    <div class="clearfix"></div>
</div>
</div>

hitarget/templates/hitarget/components/lead_maxi.html
{% load l10n %}

<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-6 col-l-6 col-xl-4">
        <div class="panel panel-default">
            <!--<div class="panel-heading">-->
                <!--{{lead.main_title}}-->
                <!--<div class="clearfix"></div>-->
            <!--</div>-->
            <div class="panel-body">
                <h3>De quoi ça parle ?</h3>
                <p>Dans le domaine {{lead.category|title}}</p>
                <p>{{lead.description_short}}</p>

                <h3>Quand?</h3>
                <ul>
                    <li>Info publiée le {{lead.date_publish|date:"D d M Y"|localize}}
                    <li>Valable pendant {{lead.expires_in_full|lower}}
                </ul>

                <h3>A propos du prospect</h3>
                <ul>
                <li>Est basé à {{lead.location}}
                <li>En ce moment: {{lead.prospect_maturity}}
                </ul>

                <h3>A propos de l'auteur</h3>
                <div class="media">
                    <a class="pull-left" href="#">
                        <img class="media-object avatar" width="60px" src="{{lead.author_avatar}}"
                             alt="{{lead.author_avatar_alt}}"/>

                    </a>
                    <div class="media-body">
                        <h4 class="media-heading">{{lead.author | title}}</h4>
                        <ul>
                            <li>est sur HiTarget depuis 3 semaines
                        </ul>

                    </div>
                </div>
            </div>
        </div>
        <div>
            <small class="pull-left date">&nbsp;{{lead.relative_date}}</small>
        </div>
        <div class="btn-group btn-group-sm pull-right" role="group" aria-label="...">
            {% for act in associated_actions %}
            <a href="{{act.url}}" class="btn btn-default {{act.additional_class}}" role="button"><i
                    class="glyphicon {{act.icon}}"></i>{{act.text}}</a>
            {% endfor %}

        </div>
        <div class="clearfix"></div>
    </div>
</div>

hitarget/templates/hitarget/components/lead_mini.html
<div class="col-xs-12 col-sm-12 col-md-6 col-l-6 col-xl-4">
    <div class="panel panel-default">
        <div class="panel-heading">

            {{lead.main_title}}
            <div class="clearfix"></div>

        </div>
        <div class="panel-body">
            <div class="media">
                <a class="pull-left" href="#">
                    <img class="media-object avatar" width="60px" src="{{lead.author_avatar}}"
                         alt="{{lead.author_avatar_alt}}"/>

                </a>
                <div class="media-body">
                    <h4 class="media-heading">{{lead.media_heading}}</h4>
                    <p>{{lead.introductory_text}}</p>
                </div>
            </div>
        </div>
        <div>
            <small class="pull-left date">&nbsp;{{lead.relative_date}}</small>
        </div>
        <div class="btn-group btn-group-sm pull-right" role="group" aria-label="...">
            {% for act in associated_actions %}
            <a href="{{act.url}}" class="btn btn-default {{act.additional_class}}" role="button"><i
                    class="glyphicon {{act.icon}}"></i>{{act.text}}</a>
            {% endfor %}
            <!--<button type="button" class="btn btn-default">-->
            <!--<i class=" glyphicon glyphicon-remove"></i>-->
            <!--</button>-->
            <!--<button type="button" class="btn btn-default">-->
            <!--<i class="glyphicon glyphicon-heart-empty"></i>-->
            <!--</button>-->
            <!--<button type="button" class="btn btn-info btn-xs pull-right">Voir plus</button>-->
        </div>
        <div class="clearfix"></div>
    </div>
</div>

hitarget/templates/hitarget/components/sample_stats.html
{% load static %}
<div class="col-xs-12 col-sm-12 col-md-6 col-l-6 col-xl-4">
    <div class="panel panel-success">
        <div class="panel-heading">
            Vendu!
        </div>
        <div class="panel-body">

            <div class="media">
                <a class="pull-left" href="#">
                    <img class="media-object avatar" src="{% get_media_prefix %}/smart_user.jpg" alt="Image">
                </a>
                <div class="media-body">
                    <p>Arthur G. souhaite acquérir votre lead "Parc d'impression réseau"</p>
                </div>
            </div>

        </div>
        <div>
            <small class="pull-left date">&nbsp;Le mardi 12.02.20017</small>
        </div>
        <div class="btn-group btn-group-sm pull-right" role="group" aria-label="...">
            <button type="button" class="btn btn-default">Refuser</button>
            <a href="#" class="btn btn-danger">Accepter</a>
        </div>
        <div class="clearfix"></div>
    </div>

</div>


<div class="col-xs-12 col-sm-12 col-md-6 col-l-6 col-xl-4">
    <div class="panel panel-warning">
        <div class="panel-heading">
            Votre lead "Infrastructure HP" ne s'est pas vendu
        </div>
        <div class="panel-body">Malheuresement, aucun des 373 visiteurs n'a voulu l'acquérir</div>
        <div>
            <small class="pull-left date">&nbsp;Il y a 3 jours</small>
        </div>
        <div class="btn-group btn-group-sm pull-right" role="group" aria-label="...">
            <button type="button" class="btn btn-default">Dommage...</button>
            <a href="#" class="btn btn-danger">Relancer!</a>
        </div>
        <div class="clearfix"></div>

    </div>


</div>


<div class="col-xs-12 col-sm-12 col-md-6 col-l-6 col-xl-4">
    <div class="panel panel-info">
        <div class="panel-heading">
            <i class="glyphicon glyphicon-signal"></i>&nbsp; De nouvelles visites sur vos leads!
        </div>
        <div class="panel-body">
            Depuis le 10.02.2017 :
            <table class="table">
                <thead>
                <tr>
                    <th>Lead</th>
                    <th>Visites</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td><a href="#">Fiches réseaux</a></td>
                    <td>+23 <i class="glyphicon glyphicon-fire"></i></td>
                </tr>
                <tr>
                    <td><a href="#">Imprimantes design</a></td>
                    <td>+3</td>
                </tr>
                </tbody>
            </table>


        </div>
        <div class="btn-group btn-group-sm pull-right" role="group" aria-label="...">
            <a href="#" class="btn btn-danger">Voir plus de stats</a>
        </div>
        <div class="clearfix"></div>


    </div>
</div>

hitarget/templates/hitarget/components/tips.html
{% load static %}
<div class="col-xs-12 col-sm-12 col-md-6 col-l-6 col-xl-4">
    <div class="panel panel-info">
        <div class="panel-heading">
            <h3 class="panel-title pull-left">Les 6 règles d'or pour des leads qui partent</h3>
            <div class="clearfix"></div>
        </div>
        <div class="panel-body">
            <div class="media">
                <a class="pull-left" href="#">
                    <img class="media-object avatar" width="60px" src="{% get_media_prefix %}/smart_user.jpg"
                         alt="arthur-g-avatar"/>

                </a>
                <div class="media-body">
                    <h4 class="media-heading">Quelques conseils!</h4>
                    <p>À votre avis, qu'est ce qui fait que des leads partent et d'autres non? L'avis de Yacine B.,
                        directeur commercial chez ... </p>
                </div>
            </div>
        </div>
        <div>
            <small class="pull-left date">&nbsp;Aujourd'hui</small>
        </div>
        <div class="btn-group btn-group-sm pull-right" role="group" aria-label="...">
            <!--<button type="button" class="btn btn-default">-->
                <!--<i class="glyphicon glyphicon-remove"></i>-->
            <!--</button>-->
            <!--<button type="button" class="btn btn-default">-->
                <!--<i class="glyphicon glyphicon-heart-empty"></i>-->
            <!--</button>-->
            <a href="/leads/tips" class="btn btn-info btn-xs pull-right">Voir plus</a>
        </div>
        <div class="clearfix"></div>
    </div>
</div>

hitarget/templates/hitarget/components/tips_6_tips.html
<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-6 col-l-6 col-xl-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                Les 6 règles d'or pour des leads qui partent
                <div class="clearfix"></div>
            </div>
            <div class="panel-body">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam, esse hic maiores nobis numquam placeat rem voluptatem. Atque eos error ex impedit ipsum modi non quibusdam recusandae! A commodi, illum.
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deleniti laboriosam placeat sapiente. Ad cum debitis eligendi incidunt ipsa ipsam laboriosam nam quaerat? Ad animi, cumque dolorum numquam ratione sunt tempora.
            </div>

            </div>
        </div>
        <div>
            <small class="pull-left date">&nbsp;{{lead.relative_date}}</small>
        </div>
        <div class="clearfix"></div>
    </div>
</div>

hitarget/templates/hitarget/components/welcome.html
<div class="col-xs-12 col-sm-12 col-md-6 col-l-6 col-xl-4">
    <div class="panel panel-info">
        <div class="panel-heading">On fait quoi?</div>
        <div class="panel-body">
            Bienvenu sur HiTarget! Voudriez-vous:
            <ul>
                <li><a href="/account/dashboard/">Rajoutez des infos sur votre compte</a></li>
                <li><a>Comprendre le principe</a></li>
                <li><a href="/leads/add">Postez votre premier lead ! </a></li>
                <li><a>Déterminez vos secteurs d'activités et nous laisser vous trouvez des leads</a></li>
                <li><a href="{% url 'hitarget:search_leads' %}">Utilisez la barre de recherche pour trouver des leads</a></li>
            </ul>

        </div>

    </div>
</div>